title: Nazmul Islam
description: A continuous learner
author: Nazmul Islam


show_downloads: false


# theme: jekyll-theme-merlot
markdown: kramdown


sass_dir: _sass
sass:
  load_paths:
    - "assets/css"
    - "_sass"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title